# Generated by Django 4.2 on 2023-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(max_length=50, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='изображение')),
                ('category', models.CharField(verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('date_create', models.DateField(verbose_name='дата создания')),
                ('date_last', models.DateField(verbose_name='дата последнего изменения ')),
            ],
        ),
    ]
