# Generated by Django 4.2 on 2023-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название статьи')),
                ('slug', models.CharField(max_length=150, verbose_name='человекопонятный url')),
                ('data', models.TextField(verbose_name='cодержимое статьи')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='изображение')),
                ('date_create', models.DateField(verbose_name='дата создания')),
                ('views_count', models.IntegerField(default=0, verbose_name='счетчик просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная статья')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('title',),
            },
        ),
    ]
